name: flutter_form_kit
description: FlutterFormKit -  An OpenSource Typeform Alternative made using Flutter
version: 0.0.3
homepage: https://github.com/YashMakan/flutter_form_kit

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_sizer: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
